### ISSUE TITLE
Report broken link 

### ISSUE THREAD

**Issue by tatticoder** [hellerve/programming-talks#103]
`Concurrency Is Not Parallelism [00:31:22] by Rob Pike (2013)` talk in Go language  programming section is no longer accessible via the link provided in this repo. It would be best to update the link or remove the entry from list

**Comment by katrinleinweber** [comment]
[Several other versions](https://www.youtube.com/results?search_query=%22Concurrency+Is+Not+Parallelism%22+%22Rob+Pike%22) of the talk are still accessible, though :-)

**Comment by hellerve** [comment]
Hey! Thank you for contributing <3

I’m currently on parental leave and am mostly focused on taking care of my child, trying not to spend too much time in front of my computer. I’ll try and find a suitable alternative version when I find the time and mental space, but it’ll probably be until next month, because that means I need to watch the talk at least once.

See you then!

**Comment by hellerve** [comment]
The link should be fixed! Thanks again!
