### ISSUE TITLE
Mark talks that can be used audio-only

### ISSUE THREAD

**Issue by NightMachinery** [hellerve/programming-talks#58]
Sometimes we can’t afford to see the video, so knowing which talks don’t lose value in audio form is very beneficial.

**Comment by hellerve** [comment]
That’s an interesting proposal!

I’d be open for that, but I don’t think I have the bandwidth to mark all of the talks that are already on the list. Would you be willing to do that?

Also, do you have a format in mind already that should be used to mark those talks?

**Comment by catb0t** [comment]
I think a trailing `[A]` to mark talks looks good and won't screw up the years script (maybe use a different brace kind), and can be parsed out by a machine, maybe:

```markdown
* [Audio talk](url) [duration] by **presenter** (year) [A]
* [Needs video](url) [duration] by **presenter** (year)
```
* [Audio talk](url) [duration] by **presenter** (year) [A]
* [Needs video](url) [duration] by **presenter** (year)

**Comment by NightMachinery** [comment]
@hellerve  @catb0t I unfortunately don’t have enough time to do this systematically, but I don’t think we need to do this for all the talks at once. We can ask people to mark any talk they watch. I think this format would serve such a crowdsourced data better: [A0/V0], in which the number after A is the number of people who think it works with just the audio, and the number after V shows the people who deem the video essential. Over time, this scheme should mark virtually all the talks. Though opening PRs for such small changes seems a bit daunting ... Can anything be done about that?

**Comment by hellerve** [comment]
I actually prefer the version @catb0t suggests.

The idea by @NightMachinary seems nice, but a little overengineered for me, and would require some tooling for people to make it simple—and I don’t really want to introduce tooling to this repository. Does that make sense?

**Comment by catb0t** [comment]
@NightMachinary 
> I don't think we need to do this for all the talks at once... [somehow suggest] people to mark any talk they watch

Exactly! -- in the case of the format I suggested, I'd watch / listen to a talk and afterward make a PR (or  edit my own `audio` branch so that I can make one big PR with a build-up of `[A]`'s I've added)

> `[An/Vn]` where n is the number of people voting for audio-only or needs-video

I think this kind of data collection would work well on a website or something with interactive voting interfaces that don't require committing and making a PR just to increment a number by 1, git/GitHub is not exactly ideal though (especially since people's forks become out-of-date just for incrementing a number, not a real change)

I don't think crowdsourcing the data is necessary for such a small piece of metadata anyway -- someone submits a PR adding some `[A]`s and maybe it would be nice for them to include a brief general explanation of why these talks are audio only, the generic "the slides are not really key explanatory visuals"  or whatever. 

If someone else listens to it / watches it and strongly thinks the visuals are important, they might be bothered to make a PR / issue to change it back. 

Hopefully this doesn't lead to Wikipedia edit warring, but a note at the top of the README like 

> **[A]** denotes a talk that *someone* thought could be listened to as audio, without needing the video. This may not reflect your experience with the talk, but if you feel strongly you can make a pull request to change it.

might help people to think of the [A] as just a suggestion.

**Comment by hellerve** [comment]
I think those suggestions all sound pretty reasonable to me!

I don’t think people usually feel super strongly about the metadata in this repository, so I don’t anticipate an "edit warring" situation; I might be mistaken, though, and I think it’s great that you’re thinking about that!

I’m also all for the suggested disclaimer at the top.

**Comment by NightMachinery** [comment]
I think we should also have a [V] tag. And yeah, I agree that my numbered
scheme doesn’t work with Github. If everything’s settled, can you finalize
it?

**Comment by catb0t** [comment]
I'm finishing up my `audio` branch's first commit just now :) 

Where does the `[V]` get used? On every talk, or just ones that *really* need video? If we add one of these `[X]` tags to every talk, the file is going to get quite ugly, much more than scattering `[A]`s...

**Comment by NightMachinery** [comment]
👍🏼
It’s better to keep things simple, either the video is essential or it’s
not. If you think marking them all is ugly, then okay, I also don’t think
[V] is that helpful. Its main use is just showing which talks have been
covered by our scheme, anyways.
