### ISSUE TITLE
Mike Acton and other "Data-Oriented" talks

### ISSUE THREAD

**Issue by pepasflo** [hellerve/programming-talks#65]
A lot of the thought in the Clojure circles can be considered "Data-oriented", but that's usually from a very high-level perspective.  Mike Acton gives a talk where explores similar ideas, but at the opposite extreme -- e.g. considering "how many bytes of this L1 cache read were actually useful?", etc.  Really interesting!

https://www.youtube.com/watch?v=rX0ItVEVjHc

I then found an entire list of "Data-oriented" talks.  Do you also include links to other "talks" lists?

https://github.com/dbartolini/data-oriented-design

**Comment by hellerve** [comment]
Thank you for submitting a link! I’ll have a look ASAP!

As per your question on including other lists: I did it once, with Python, and it’s linked to from the Python section. We sadly do not have a data-oriented design section. We do have a Data Science section, but that would seem a little displaced to me. Do you have any suggestions where this could go?

**Comment by pepasflo** [comment]
My guess would be "software development" for now, as it seems like sub-category of programming methodology.

**Comment by hellerve** [comment]
I’m not super happy with the tone of Mike Acton’s talk, it’s a little hostile and very hurried; maybe someone else could say something about whether they enjoyed the talk or not (this is how I usually resolve these things when my subjective bias might make me fail to see the merit of a talk).

Also, would you like to open a PR that adds this to the list (and maybe a link to the other list as well) or would you prefer me to do that?

**Comment by catb0t** [comment]
Hmm, I think Acton is  mostly a very nervous / new public speaker, I know talked way too fast the first time I was on stage with a microphone. 

I don't agree with him, but I think his perspective is useful if slightly tainted by the games industry, and his abrasiveness shouldn't be normalised but I have to say I prefer it over people who badly fake a smile and happy tone on stage, if that makes sense.

**Comment by hellerve** [comment]
That totally makes sense. I mostly got annoyed by his short temper with people who question his reasoning. In my opinion, the Q&A was a total trainwreck of clashing egos.

I do understand that his perspective adds value, however, and I think including this talk would make sense. There is something of value here, even if I can’t see it; I defer to the wisdom of the crowd.

<details>
<summary>Personal experiences with public speaking noone cares about + more subjective opinion about Mike Acton’s talk that is not worth being part of the actual discussion</summary>

This year, I gave variations on the same talk four times. I overpracticed it (because I practiced it before every talk), and it subjectively actually got worse after the second time. I hear that it was actually enjoyable, but I’m glad that only the second variation (see [here](https://www.youtube.com/watch?v=BQeG6fXMk28)) actually made it to the internet.

I understand speaker anxiety; I understand speakers being irritable. But I still think that the talk that Mike Actond delivered didn’t do his message justice. This is entirely subjective—everyone has their own presentation style—, but I just think it’s a bummer, because I really want to hear about the constraints of various industries. I’ve heard people from the VST—synthesizers that do analogue modelling especially—voice the same kind of ideas and constraints in a much more concise and interesting way, but adhoc and not in a conference setting. So I guess for me this is a situation where we have to settle. This is not meant as a slight against Mike Acton, who I believe to be a great engineer; I just think he didn’t voice his concerns as eloquently and as understandably as he could have. Instead he chose to almost explode at people who were coming from a different area of engineering that has just as much merit as his niche.
</details>

**Comment by hellerve** [comment]
Just FYI, my last reply doesn’t mean I’m not open to a PR about this; if you want to add this @pepasflo or you want me to add it, just give me a quick heads-up! 😸

**Comment by catb0t** [comment]
Alternatively,

I found another, more recent CppCon talk about the same thing, using data-oriented design as an optimisation over OOP, and the speaker is much nicer / relaxed. Also, he talks specifically about the topic, organising data design, and less about assembly-level cache sizes.

And, when Nikolov puts it this way, I see exactly what he means and I agree with him, whereas I now think Acton's framing is a little vague or blurring.

> * [OOP Is Dead, Long Live Data-oriented Design](https://www.youtube.com/watch?v=yy8jQgmhbAU) [01:00:45] by **Stoyan Nikolov** (2018)

```markdown
* [OOP Is Dead, Long Live Data-oriented Design](https://www.youtube.com/watch?v=yy8jQgmhbAU) [01:00:45] by **Stoyan Nikolov** (2018)
```

If @pepasflo likes it, you could put that *instead* of Acton -- otherwise, I'll definitely add it later.

**Comment by pepasflo** [comment]
Sounds good, let's go with Nikolov!

**Comment by pepasflo** [comment]
PR!  https://github.com/hellerve/programming-talks/pull/67

Thanks @catb0t 😸
